version: '3.9'

services:
  front:
    image: hamyarchat/front:latest
    deploy:
      replicas: 1
      # placement:
      #   constraints:
      #     - node.role == master
      resources:
        limits:
          cpus: '2'
          memory: 2048M
      restart_policy:
        condition: any
    ports:
      - "3000:3000"
    networks:
      - hamyarchat-net

  langchain:
    image: hamyarchat/langchain:latest
    deploy:
      replicas: 1
      # placement:
      #   constraints:
      #     - node.role == worker
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      restart_policy:
        condition: any
    ports:
      - "8000:8000"
    networks:
      - hamyarchat-net

  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: hamyarchat
  #     POSTGRES_PASSWORD: secret
  #     POSTGRES_DB: hamyarchatdb
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints:
  #         - node.labels.role == worker
  #     resources:
  #       limits:
  #         cpus: '0.25'
  #         memory: 256M
  #     restart_policy:
  #       condition: on-failure
  #   networks:
  #     - hamyarchat-net

  # minio:
  #   image: quay.io/minio/minio:RELEASE.2023-11-01T01-57-10Z-cpuv1
  #   deploy:
  #     replicas: 1
  #     resources:
  #       limits:
  #         cpus: '1'
  #         memory: 1024M
  #     restart_policy:
  #       condition: any
  #   environment:
  #     - MINIO_ROOT_USER=admin
  #     - MINIO_ROOT_PASSWORD=admin123
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   volumes:
  #     - minio-data:/data
  #   command: server /data --console-address ":9001"
  #   networks:
  #     - hamyarchat-net

networks:
  hamyarchat-net:

# volumes:
#   minio-data:


  